name: Push To Repo

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.1
    - name: Set up JDK 11.0.14+101
      uses: actions/setup-java@v3.11.0
      with:
        distribution: 'temurin'
        java-version: '11.0.14+101'
    - name: Build with Maven
      run: mvn package --file pom.xml
    - if: github.event.release
      name: Update version in pom.xml (Release only)
      run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false
    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: project

    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://repo.thedutchruben.nl/
        username: admin
        password: ${{ secrets.SONAR_TOKEN }}
        format: maven2
        repository: maven-releases
        coordinates: groupId=nl.thedutchruben artifactId=tdrplaytime version=${{ steps.project.outputs.version }}
        assets: extension=jar
        filename: ./target/playtime-${{ steps.project.outputs.version }}.jar
